@@ portable

open! Base
open! Import
module Hlist = Hlist

(** [t] is the type of implementations of parallelism. Operations that produce parallel
    subtasks take a [t] that provides an implementation of parallelism for them to use. *)
type t : value mod contended non_float portable

(** A trivial implementation of parallelism that runs all subtasks sequentially. *)
val sequential : t

(** [sync t] is an [Await.Sync.t] that may be used to acquire locks inside parallel
    functions. To do nested parallelism while holding a lock, use [Parallel.Capsule]. *)
val sync : t @ local -> Sync.t @ local

module Thunk : sig
  type nonrec 'a t = t @ local -> 'a
end

(** [fork_join t fs] runs the functions in the heterogenous list [f] as parallel subtasks
    and returns their results. If any subtask raises, this operation will reraise the
    leftmost exception after all subtasks have completed or raised. *)
val fork_join : t @ local -> 'l Hlist.Gen(Thunk).t @ once shareable -> 'l Hlist.t

(* $MDX part-begin=fork_join2 *)

(** [fork_join2 t f g] runs [f] and [g] as parallel subtasks and returns their results. If
    either subtask raises, this operation will reraise the leftmost exception after both
    subtasks have completed or raised.

    [f] and [g] are [shareable], so can capture both [shared] and [uncontended]
    references. This allows the subtasks to read (but not mutate) state from the
    environment. [f] is also [forkable], so cannot capture capsule passwords. *)
val fork_join2
  :  t @ local
  -> (t @ local -> 'a) @ forkable local once shareable
  -> (t @ local -> 'b) @ once shareable
  -> #('a * 'b)

(* $MDX part-end *)

(** See {!fork_join2} *)
val fork_join3
  :  t @ local
  -> (t @ local -> 'a) @ forkable local once shareable
  -> (t @ local -> 'b) @ once shareable
  -> (t @ local -> 'c) @ once shareable
  -> #('a * 'b * 'c)

(** See {!fork_join2} *)
val fork_join4
  :  t @ local
  -> (t @ local -> 'a) @ forkable local once shareable
  -> (t @ local -> 'b) @ once shareable
  -> (t @ local -> 'c) @ once shareable
  -> (t @ local -> 'd) @ once shareable
  -> #('a * 'b * 'c * 'd)

(** See {!fork_join2} *)
val fork_join5
  :  t @ local
  -> (t @ local -> 'a) @ forkable local once shareable
  -> (t @ local -> 'b) @ once shareable
  -> (t @ local -> 'c) @ once shareable
  -> (t @ local -> 'd) @ once shareable
  -> (t @ local -> 'e) @ once shareable
  -> #('a * 'b * 'c * 'd * 'e)

module Biased : sig
  (** Like {!fork_join2}, but runs the leftmost subtask in the current capsule. *)
  val fork_join2
    :  t @ local
    -> (t @ local -> 'a) @ local once
    -> (t @ local -> 'b) @ once portable
    -> #('a * 'b)

  (** Like {!fork_join3}, but runs the leftmost subtask in the current capsule. *)
  val fork_join3
    :  t @ local
    -> (t @ local -> 'a) @ local once
    -> (t @ local -> 'b) @ once portable
    -> (t @ local -> 'c) @ once portable
    -> #('a * 'b * 'c)

  (** Like {!fork_join4}, but runs the leftmost subtask in the current capsule. *)
  val fork_join4
    :  t @ local
    -> (t @ local -> 'a) @ local once
    -> (t @ local -> 'b) @ once portable
    -> (t @ local -> 'c) @ once portable
    -> (t @ local -> 'd) @ once portable
    -> #('a * 'b * 'c * 'd)

  (** Like {!fork_join5}, but runs the leftmost subtask in the current capsule. *)
  val fork_join5
    :  t @ local
    -> (t @ local -> 'a) @ local once
    -> (t @ local -> 'b) @ once portable
    -> (t @ local -> 'c) @ once portable
    -> (t @ local -> 'd) @ once portable
    -> (t @ local -> 'e) @ once portable
    -> #('a * 'b * 'c * 'd * 'e)
end

(** [for_ t ~start ~stop ~f] runs [f t i] as a parallel subtask for each [i] in the range
    [start..stop-1].

    If any invocation of [f] raises, this operation will reraise the leftmost exception.
    If an exception occurs at index [i], [f] may or may not be invoked for any [j > i]. *)
val for_
  :  t @ local
  -> start:int
  -> stop:int
  -> f:(t @ local -> int -> unit) @ shareable
  -> unit

(** [fold t ~init ~state ~next ~stop ~fork ~join] folds an accumulator over a sequence of
    states generated by [next]. The initial accumulator is [init ()] and the initial state
    is [state]. At each step, [next t state acc] is applied to get the next accumulator
    and state. When [next] returns [None], the current accumulator is passed to [stop] and
    then returned as the result of [fold].

    [init], [stop], [fork], and [join] allow the scheduler to split states into parts that
    may be folded in parallel, then recombined with [join]. Given a state [s], [fork s]
    returns two states [s0, s1] such that:

    [stop (fold acc s) = join (stop (fold acc s0)) (stop (fold (init ()) s1))]

    The operation implemented by the callbacks must be associative, and [init] must return
    a neutral element. If this is not the case, results will be non-deterministic. *)
val%template fold
  : ('acc : acc) ('seq : seq mod shareable shared).
  t @ local
  -> init:(unit -> 'acc) @ portable
  -> state:'seq
  -> next:(t @ local -> 'acc -> 'seq -> (#('acc * 'seq) Option_u.t[@kind acc & seq]))
     @ shareable
  -> stop:(t @ local -> 'acc -> 'ret) @ shareable
  -> fork:(t @ local -> 'seq -> (#('seq * 'seq) Option_u.t[@kind seq & seq])) @ shareable
  -> join:(t @ local -> 'ret -> 'ret -> 'ret) @ shareable
  -> 'ret
[@@kind
  acc = (base_or_null, value_or_null & base_or_null)
  , seq = (base_or_null, value_or_null & value_or_null)]

(** [heartbeat t ~n] allows [n] subtasks to be promoted to tasks. If there are fewer than
    [n] subtasks in the current queue, the remaining count will be used to eagerly promote
    new subtasks. If [n < 0], the next [n] promotions will be skipped. *)
val heartbeat : t @ local -> n:int -> unit

module Lazy : Await_sync.Expert.Lazy.S with type capability := t

module For_scheduler : sig
  module Result = Result

  (** [root_exn f ~task ~subtask ~try_wake] creates a top-level, schedulable task
      representing the full execution of [f]. The functions [f], [task], [subtask], and
      [wake] must not raise exceptions. All schedulers must use [root_exn] to create the
      initial portable function they inject into the worker pool.

      The functions [task], [subtask], and [try_wake] define the behavior of the
      scheduler. When the heartbeat mechanism determines enough work has occurred to
      amortize promotion overhead, it calls [subtask], which gives the scheduler an
      opportunity to distribute subtasks to other domains. After promoting [n] subtasks,
      [try_wake ~n] is called, which tells the scheduler how many workers it may want to
      wake up. If a heartbeat occurs during [subtask] or [try_wake], they may be
      re-entered. Tasks scheduled from outside the scheduler - and tasks that suspend
      using [Await.await await] or [Await.yield await] - are passed to [task] when
      signaled.

      @raise Out_of_fibers if unable to allocate a fiber. *)
  val root_exn
    :  unit Thunk.t @ once portable
    -> task:((unit -> unit) @ once portable -> unit) @ portable
    -> subtask:((unit -> unit) @ once portable -> unit) @ portable
    -> try_wake:(n:int -> unit) @ portable
    -> (unit -> unit) @ once portable

  (** [await t terminator] is an [Await.t] that suspends the current task and resubmits it
      to the global queue when signaled. *)
  val await : t @ local -> Terminator.t @ local -> Await.t @ local

  (** [with_heartbeat f] assures the heartbeat thread is running for the duration of [f]. *)
  val with_heartbeat
    : ('a : value_or_null).
    (unit -> 'a @ once unique) @ local once -> 'a @ once unique

  (** [without_heartbeat f] masks heartbeats for the duration of [f]. *)
  val without_heartbeat
    : ('a : value_or_null).
    (unit -> 'a @ once unique) @ local once unyielding -> 'a @ once unique
end

module For_testing : sig
  module Runqueue : sig
    type t

    val create : unit -> t @ local
    val tokens : t @ local -> int

    val with_jobs
      :  t @ local
      -> ('l * 'll) Hlist.Gen(Thunk).t @ once portable
      -> f:(t @ local -> unit) @ local
      -> unit

    val promote : t @ local -> n:int -> f:(tokens:int -> unit) @ local -> unit
  end
end
