@@ portable

open! Base
open! Import
module Hlist = Hlist
module Panic = Panic
module Monitor = Panic.Monitor

(** [Panic p] is an exception indicating that a panic [p] has occurred. *)
exception Panic of Panic.t
[@@deriving sexp_of]

(** [t] is the type of implementations of parallelism. Operations that produce parallel
    tasks take a [t] that provides an implementation of parallelism for them to use. *)
type t : value mod contended portable

(** [panic t i] reports the incident [i] to the current monitor and raises [Panic]. *)
val panic : t @ local -> Panic.Incident.t -> 'a @ portable unique

module Thunk : sig
  type nonrec 'a t = t @ local -> 'a
end

(** [fork_join t fs] runs the functions in the heterogenous list [f] as parallel tasks and
    returns their results. If any task panics or raises an uncaught exception, this
    operation will raise [Panic] once all tasks have completed or panicked.

    Child tasks must not block on each other or the parent task, but they may take locks. *)
val fork_join
  :  t @ local
  -> 'a Hlist.Gen(Thunk).t @ once portable unyielding
  -> 'a Hlist.t

(* $MDX part-begin=fork_join2 *)

(** [fork_join2 t f g] runs [f] and [g] as parallel tasks and returns their results. If
    either task panics or raises an uncaught exception, this operation will raise [Panic]
    once both tasks have completed or panicked.

    Child tasks must not block on each other or the parent task, but they may take locks. *)
val fork_join2
  :  t @ local
  -> (t @ local -> 'a) @ once portable unyielding
  -> (t @ local -> 'b) @ once portable unyielding
  -> 'a * 'b

(* $MDX part-end *)

(** See {!fork_join2} *)
val fork_join3
  :  t @ local
  -> (t @ local -> 'a) @ once portable unyielding
  -> (t @ local -> 'b) @ once portable unyielding
  -> (t @ local -> 'c) @ once portable unyielding
  -> 'a * 'b * 'c

(** See {!fork_join2} *)
val fork_join4
  :  t @ local
  -> (t @ local -> 'a) @ once portable unyielding
  -> (t @ local -> 'b) @ once portable unyielding
  -> (t @ local -> 'c) @ once portable unyielding
  -> (t @ local -> 'd) @ once portable unyielding
  -> 'a * 'b * 'c * 'd

(** See {!fork_join2} *)
val fork_join5
  :  t @ local
  -> (t @ local -> 'a) @ once portable unyielding
  -> (t @ local -> 'b) @ once portable unyielding
  -> (t @ local -> 'c) @ once portable unyielding
  -> (t @ local -> 'd) @ once portable unyielding
  -> (t @ local -> 'e) @ once portable unyielding
  -> 'a * 'b * 'c * 'd * 'e

(** [for_ ?grain t ~start ~stop ~f] runs [f t i] as a parallel task for each [i] in the
    range [start..stop-1]. If [f t i] panics or raises an uncaught exception, this
    operation will raise [Panic], and [f t j] may or may not be invoked for any [j > i].
    If [grain] is specified, blocks of [grain] indices will constitute a single parallel
    task. *)
val for_
  :  ?grain:int
  -> t @ local
  -> start:int
  -> stop:int
  -> f:(t @ local -> int -> unit) @ portable
  -> unit

(** [fold ?grain t ~init:(zero, state) ~next ~fork ~join] folds an accumulator over a
    sequence of states generated by [next]. The initial accumulator is [zero] and the
    initial state is [state]. At each step, [next t state acc] is applied to get the next
    accumulator and state. When [next] returns [None], the current accumulator is returned
    as the result of [fold]. If [grain] is specified, blocks of [grain] indices will
    constitute a single parallel task.

    [fork] and [join] allow the scheduler to split states into parts that may be folded in
    parallel, then recombined with [join]. Given a state [s], [fork s] returns two states
    [s0, s1] such that [fold s = join (fold s0) (fold s1)].

    The operation implemented by [next], [fork], and [join] must be associative, and
    [zero] must be a neutral element. If this is not the case, results will be
    non-deterministic. *)
val fold
  :  ?grain:int
  -> t @ local
  -> init:#('acc * 's) @ contended portable
  -> next:
       (t @ local
        -> 'acc @ contended portable
        -> 's @ contended portable
        -> ('acc, 's) Pair_or_null.t @ contended portable)
     @ portable
  -> fork:
       (t @ local
        -> 's @ contended portable
        -> ('s, 's) Pair_or_null.t @ contended portable)
     @ portable
  -> join:
       (t @ local
        -> 'acc @ contended portable
        -> 'acc @ contended portable
        -> 'acc @ contended portable)
     @ portable
  -> 'acc @ contended portable

module Scheduler : sig
  module type S = Parallel_scheduler_intf.S with type parallel := t
  module type S_async = Parallel_scheduler_intf.S_async with type parallel := t

  (** A trivial implementation of parallelism that runs all tasks sequentially. *)
  module Sequential : sig
    include S with type 'k create_fn := 'k

    val create : unit -> t
  end

  (** [check_heartbeat t] provides an opportunity to share pending work with other
      domains. Calls to [fork_join] have the same effect, so [check_heartbeat] should only
      be used during long-running tasks that do not otherwise call [fork_join]. *)
  val check_heartbeat : t @ local -> unit
end

module For_scheduler : sig
  module Ivar = Ivar

  (** [root ~promote ~wake ~monitor ~f] creates a top-level, schedulable task representing
      the full execution of [f]. It is unsafe for the functions [promote] and [wake] to
      raise exceptions. All schedulers must use [root] to create the initial portable
      function they inject into the worker pool. Uncaught exceptions raised by [f] will be
      reported to [monitor].

      The functions [promote] and [wake] define the behavior of the scheduler. Upon
      heartbeating, [promote] is called on up to [Env.max_promotions] tasks that have not
      yet been shared with the scheduler. This gives the scheduler an opportunity to
      distribute work to other domains. At the end of a heartbeat, [wake ~n] is called,
      where [n] is the number of promoted jobs. This tells the scheduler how many workers
      it may want to wake up. *)
  val root
    :  monitor:Monitor.t
    -> promote:((unit -> unit) @ once portable -> unit) @ portable
    -> wake:(n:int -> unit) @ portable
    -> f:unit Thunk.t @ once portable
    -> (unit -> unit) @ once portable
end

module For_testing : sig
  module Runqueue : sig
    type t

    val create : unit -> t @ local

    val with_jobs
      :  t @ local
      -> ('l * 'll) Hlist.Gen(Thunk).t @ once portable
      -> f:(t @ local -> unit) @ local
      -> unit

    val promote : t @ local -> n:int -> f:(unit -> unit) @ local -> unit
  end
end
